# Generated by Django 5.2.3 on 2025-06-12 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'gen_clinic',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('specialization', models.CharField(max_length=100)),
                ('available_days', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalapi.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gen_doctor',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapi.doctor')),
            ],
            options={
                'db_table': 'gen_doctoravailability',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('dob', models.DateField(db_column='date_of_birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('O', 'Other')], default='M')),
                ('phone_number', models.CharField(max_length=15)),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gen_patient',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('medicalrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalapi.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapi.patient')),
            ],
            options={
                'db_table': 'gen_medicalrecord',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('date', models.DateField(db_column='appointment_date')),
                ('time', models.TimeField(db_column='appointment_time')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('Co', 'Confirmed'), ('Ca', 'Cancelled')], db_column='appointment_status', default='P')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapi.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalapi.patient')),
            ],
            options={
                'db_table': 'gen_appointment',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('notes', models.TextField()),
                ('medications', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicalapi.appointment')),
            ],
            options={
                'db_table': 'gen_prescription',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gen_supportticket',
            },
        ),
    ]
